apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pre-defined-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-cluster-store
  target:
    name: pre-defined-secret
  data:
    - secretKey: github_token
      remoteRef:
        key: GITHUB_TOKEN
