kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.fbi.com
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      path: /
      pathType: Prefix
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi

  prometheus:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus.fbi.com
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      paths:
        - /
      pathType: Prefix

    prometheusSpec:
      serviceMonitorNamespaceSelector:
        matchLabels: {}
      serviceMonitorSelector:
        matchLabels: {}
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          memory: 512Mi

  alertmanager:
    alertmanagerSpec:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          memory: 64Mi

  prometheusOperator:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi

  kube-state-metrics:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 64Mi

  prometheus-node-exporter:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 64Mi
