apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ou-k8sapi-tls
  namespace: openunison
spec:
  secretName: ou-k8sapi-tls
  dnsNames:
    - k8sapi.homelab.lan
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer
