{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "guestbook.fullname" . }}
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "guestbook.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from ingress controller
    - from:
      - namespaceSelector:
          matchLabels:
            name: ingress-nginx
      ports:
      - protocol: TCP
        port: {{ .Values.service.port }}
    # Allow traffic from Prometheus for metrics
    {{- if .Values.metrics.serviceMonitor.enabled }}
    - from:
      - namespaceSelector:
          matchLabels:
            name: prometheus
      ports:
      - protocol: TCP
        port: {{ .Values.service.port }}
    {{- end }}
  egress:
    # Allow DNS resolution
    - to:
      - namespaceSelector:
          matchLabels:
            name: kube-system
      ports:
      - protocol: UDP
        port: 53
    # Allow access to Redis
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: redis
            app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
      - protocol: TCP
        port: 6379
{{- end }}
