gha-runner-scale-set:
  runnerScaleSetName: gha-runner

  githubConfigUrl: https://github.com/ChapChap/argo-dojo-kube
  githubConfigSecret: pre-defined-secret

  controllerServiceAccount:
    name: gha-runner-gha-rs-controller # À variabiliser
    namespace: gha-runner

  maxRunners: 2
  minRunners: 1

  template:
    spec:
      containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        - name: DOCKER_TLS_CERTDIR
          value: ""
        - name: DOCKER_TLS_VERIFY
          value: ""
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            memory: 256Mi
        volumeMounts:
        - name: work
          mountPath: /home/runner/_work
      - name: dind
        image: docker:dind
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            memory: 256Mi
        volumeMounts:
        - name: work
          mountPath: /home/runner/_work
        - name: dind-storage
          mountPath: /var/lib/docker
      volumes:
      - name: work
        emptyDir: {}
      - name: dind-storage
        emptyDir: {}
