gha-runner-scale-set:
  runnerScaleSetName: gha-runner
  githubConfigUrl: https://github.com/ChapChap/argo-dojo-kube
  githubConfigSecret: pre-defined-secret
  controllerServiceAccount:
    name: gha-runner-gha-rs-controller # À variabiliser
    namespace: gha-runner
  maxRunners: 2
  minRunners: 1
