gha-runner-scale-set:
  runnerScaleSetName: gha-runner

  githubConfigUrl: https://github.com/ChapChap/argo-dojo-kube
  githubConfigSecret: pre-defined-secret

  controllerServiceAccount:
    name: gha-runner-gha-rs-controller # À variabiliser
    namespace: gha-runner

  maxRunners: 2
  minRunners: 1

  template:
    spec:
      containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: work
          mountPath: /home/runner/_work
        - name: dind-sock
          mountPath: /var/run
      - name: dind
        image: docker:dind
        securityContext:
          privileged: true
        volumeMounts:
        - name: work
          mountPath: /home/runner/_work
        - name: dind-sock
          mountPath: /var/run
        - name: dind-storage
          mountPath: /var/lib/docker
      volumes:
      - name: work
        emptyDir: {}
      - name: dind-sock
        emptyDir: {}
      - name: dind-storage
        emptyDir: {}
