apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-cluster-store
  target:
    name: renovate-token
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: GITHUB_TOKEN
