apiVersion: v2
name: vault
description: A Helm chart for deployment vault on Kubernetes
type: application
version: 0.31.0
dependencies:
  - name: vault
    version: 0.31.0
    repository: https://helm.releases.hashicorp.com
