vault:
  server:
    dev:
      enabled: true
    extraEnvironmentVars:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_TOKEN: "root"
    postStart:
      - "/bin/sh"
      - "-c"
      - |
        set -eu
        echo "[postStart] Waiting for Vault to be up..."
        for i in $(seq 1 60); do
          if vault status >/dev/null 2>&1; then
            break
          fi
          sleep 1
        done
        echo "[postStart] Enabling userpass auth method (idempotent)..."
        vault auth enable userpass 2>/dev/null || true
        echo "[postStart] Creating default admin user (idempotent)..."
        vault write auth/userpass/users/admin password="changeme" policies="default" 2>/dev/null || true
        echo "[postStart] Done."
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: vault.fbi.com
          paths:
            - /
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      pathType: Prefix
