apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gitlab-cluster-store
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            name: gitlab-access-token
            key: token
            namespace: external-secrets
      projectID: 75483398
