apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-access-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-cluster-store
  target:
    name: gitlab-access-token
  data:
    - secretKey: token
      remoteRef:
        key: GITLAB_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
