external-secrets:
  networkPolicy:
    enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      memory: 64Mi

  webhook:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 64Mi

  certController:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 64Mi
