name: Docker-Build-and-Push

on:
  push:

jobs:
  docker:
    runs-on: gha-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push with Kaniko
        uses: aevea/action-kaniko@master
        with:
          image: achapusot/guestbook
          tag: latest
          path: ./Docker
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
