apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: default
  destination:
    namespace: argocd
    name: in-cluster
  source:
    repoURL: https://github.com/ChapChap/argo-dojo-kube.git
    path: /argo-apps
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
