apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: customresourcedefinitions
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/ChapChap/argo-dojo-kube.git
        revision: main
        directories:
          - path: "CRDs/*"
  template:
    metadata:
      name: "{{ .path.basename }}"
      annotations:
        argocd.argoproj.io/sync-wave: '0'
    spec:
      project: default
      source:
        repoURL: https://github.com/ChapChap/argo-dojo-kube.git
        targetRevision: main
        path: "{{ .path.path }}"
        kustomize: {}
      destination:
        name: in-cluster
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
